databases:
  pg:
    dsn: postgresql+psycopg2://postgres:mysecretpassword@172.17.0.2/postgres

metrics:
  pg_process:
    type: gauge
    description: Number of PostgreSQL processes with their states
    labels: [state]

queries:
  process_stats:
    databases: [pg]
    metrics:
      - pg_process
    sql: >
      SELECT
        state,
        COUNT(*) AS pg_process
      FROM pg_stat_activity
      WHERE state IS NOT NULL
      GROUP BY state
      FROM pg_stat_database
